// <auto-generated />
using System;
using IntegrationHub.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegrationHub.Api.Migrations
{
    [DbContext(typeof(IntegrationHubDbContext))]
    [Migration("20260304083920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("IntegrationHub.Api.Data.Entities.TicketSyncMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AsanaTaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FreshdeskTicketId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TicketSyncMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
